### ISSUE TITLE
Distribute Peer ID to Websocket Mapping

### ISSUE THREAD

**Issue by georgeaf99** [peers-for-peers/the-social-server#1]
**Goal:** Allow the server to scale to multiple hosts

**Tasks:**
- [ ] Store the peer ID to responsible server mapping in a cache (online status can be derived from here)
- [ ] Store the peer ID to websocket connection map in memory
- [ ] Triage signal messages to the responsible server
